"""Add Operation3

Revision ID: 7cff0b8d5d5a
Revises: 76e6f2edf70c
Create Date: 2023-09-07 18:46:04.432331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cff0b8d5d5a'
down_revision: Union[str, None] = '76e6f2edf70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
