"""Add Operation

Revision ID: 8f9519cb1f9c
Revises: 4f2fbfcdf59e
Create Date: 2023-09-07 18:41:44.709128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9519cb1f9c'
down_revision: Union[str, None] = '4f2fbfcdf59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
